{{- if .Values.service.swarm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dscp-ipfs.fullname" . }}-swarm
  {{- with .Values.service.swarm.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dscp-ipfs.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ include "dscp-ipfs.fullname" . }}
  ports:
    - protocol: 'TCP'
      port: {{ .Values.service.swarm.port }}
      targetPort: {{ .Values.config.ipfsSwarmPort }}
{{- end }}
---
{{- if .Values.service.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dscp-ipfs.fullname" . }}-api
  {{- with .Values.service.api.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dscp-ipfs.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ include "dscp-ipfs.fullname" . }}
  ports:
    - protocol: 'TCP'
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.config.ipfsApiPort }}
{{- end }}
